import { blue } from '../constants';
import { Level } from '../types';

const fifthLevel: Level = {
    ballSpeed: 2.8,
    paddleSpeed: 8,
    paddleSize: {
        width: 35,
        height: 15,
    },
    bricks: [
        {
            x: 30,
            y: 30,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 60,
            y: 30,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 90,
            y: 30,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 120,
            y: 30,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 150,
            y: 30,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 180,
            y: 30,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 210,
            y: 30,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 240,
            y: 30,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 270,
            y: 30,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 300,
            y: 30,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 330,
            y: 30,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 360,
            y: 30,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 390,
            y: 30,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 420,
            y: 30,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 30,
            y: 60,
            color: blue,
            width: 50,
            height: 20,
        },
        {
            x: 90,
            y: 60,
            color: blue,
            width: 50,
            height: 20,
        },
        {
            x: 150,
            y: 60,
            color: blue,
            width: 50,
            height: 20,
        },
        {
            x: 210,
            y: 60,
            color: blue,
            width: 50,
            height: 20,
        },
        {
            x: 270,
            y: 60,
            color: blue,
            width: 50,
            height: 20,
        },
        {
            x: 330,
            y: 60,
            color: blue,
            width: 50,
            height: 20,
        },
        {
            x: 390,
            y: 60,
            color: blue,
            width: 50,
            height: 20,
        },
        {
            x: 30,
            y: 90,
            color: blue,
            width: 30,
            height: 20,
        },
        {
            x: 75,
            y: 90,
            color: blue,
            width: 30,
            height: 20,
        },
        {
            x: 120,
            y: 90,
            color: blue,
            width: 30,
            height: 20,
        },
        {
            x: 160,
            y: 90,
            color: blue,
            width: 30,
            height: 20,
        },
        {
            x: 200,
            y: 90,
            color: blue,
            width: 30,
            height: 20,
        },
        {
            x: 240,
            y: 90,
            color: blue,
            width: 30,
            height: 20,
        },
        {
            x: 280,
            y: 90,
            color: blue,
            width: 30,
            height: 20,
        },
        {
            x: 320,
            y: 90,
            color: blue,
            width: 30,
            height: 20,
        },

        {
            x: 360,
            y: 90,
            color: blue,
            width: 30,
            height: 20,
        },
        {
            x: 400,
            y: 90,
            color: blue,
            width: 40,
            height: 20,
        },
    ],
};

export default fifthLevel;
