import { blue } from '../constants';
import { Level } from '../types';

const fourthLevel: Level = {
    ballSpeed: 2.6,
    paddleSpeed: 7.6,
    paddleSize: {
        width: 45,
        height: 15,
    },
    bricks: [
        {
            x: 30,
            y: 30,
            color: blue,
            width: 75,
            height: 20,
        },
        {
            x: 115,
            y: 30,
            color: blue,
            width: 75,
            height: 20,
        },
        {
            x: 200,
            y: 30,
            color: blue,
            width: 75,
            height: 20,
        },
        {
            x: 285,
            y: 30,
            color: blue,
            width: 75,
            height: 20,
        },
        {
            x: 370,
            y: 30,
            color: blue,
            width: 75,
            height: 20,
        },
        {
            x: 30,
            y: 60,
            color: blue,
            width: 47,
            height: 20,
        },
        {
            x: 92,
            y: 60,
            color: blue,
            width: 47,
            height: 20,
        },
        {
            x: 154,
            y: 60,
            color: blue,
            width: 47,
            height: 20,
        },
        {
            x: 216,
            y: 60,
            color: blue,
            width: 47,
            height: 20,
        },
        {
            x: 278,
            y: 60,
            color: blue,
            width: 47,
            height: 20,
        },
        {
            x: 340,
            y: 60,
            color: blue,
            width: 47,
            height: 20,
        },
        {
            x: 402,
            y: 60,
            color: blue,
            width: 42,
            height: 20,
        },
        {
            x: 30,
            y: 90,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 60,
            y: 90,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 90,
            y: 90,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 120,
            y: 90,
            color: blue,
            width: 20,
            height: 20,
        },

        {
            x: 150,
            y: 90,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 180,
            y: 90,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 210,
            y: 90,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 240,
            y: 90,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 270,
            y: 90,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 300,
            y: 90,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 330,
            y: 90,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 360,
            y: 90,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 390,
            y: 90,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 420,
            y: 90,
            color: blue,
            width: 20,
            height: 20,
        },
    ],
};

export default fourthLevel;
