import { blue } from '../constants';
import { Level } from '../types';

const secondLevel: Level = {
    ballSpeed: 2.2,
    paddleSpeed: 7.2,
    paddleSize: {
        width: 65,
        height: 15,
    },
    bricks: [
        {
            x: 30,
            y: 30,
            color: blue,
            width: 80,
            height: 20,
        },
        {
            x: 120,
            y: 30,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 150,
            y: 30,
            color: blue,
            width: 80,
            height: 20,
        },
        {
            x: 240,
            y: 30,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 270,
            y: 30,
            color: blue,
            width: 80,
            height: 20,
        },
        {
            x: 360,
            y: 30,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 390,
            y: 30,
            color: blue,
            width: 70,
            height: 20,
        },
        {
            x: 30,
            y: 60,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 60,
            y: 60,
            color: blue,
            width: 80,
            height: 20,
        },
        {
            x: 150,
            y: 60,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 180,
            y: 60,
            color: blue,
            width: 80,
            height: 20,
        },
        {
            x: 270,
            y: 60,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 300,
            y: 60,
            color: blue,
            width: 80,
            height: 20,
        },
        {
            x: 390,
            y: 60,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 420,
            y: 60,
            color: blue,
            width: 40,
            height: 20,
        },
        {
            x: 30,
            y: 90,
            color: blue,
            width: 80,
            height: 20,
        },
        {
            x: 120,
            y: 90,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 150,
            y: 90,
            color: blue,
            width: 80,
            height: 20,
        },
        {
            x: 240,
            y: 90,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 270,
            y: 90,
            color: blue,
            width: 80,
            height: 20,
        },
        {
            x: 360,
            y: 90,
            color: blue,
            width: 20,
            height: 20,
        },
        {
            x: 390,
            y: 90,
            color: blue,
            width: 70,
            height: 20,
        },
    ],
};

export default secondLevel;
